from dataclasses import dataclass
from typing import Any, Iterable

STATUS_QUANTITATIVO = {"LEVANTADO", "PENDENTE_RFI", "NAO_LEVANTADO"}

COLUNAS_QUANTITATIVO = (
    "COD_EAP", "DESCRICAO_DO_SERVICO", "DISCIPLINA", "UNIDADE",
    "QUANTIDADE_TOTAL", "PRANCHA_REFERENCIA", "STATUS",
)

COLUNAS_ORCAMENTO = (
    "COD_EAP", "DESCRICAO_DO_SERVICO", "DISCIPLINA", "UNIDADE",
    "QUANTIDADE_TOTAL", "CUSTO_UNITARIO_BDI", "CUSTO_TOTAL",
    "EMPREITEIRO_VINCULADO", "PRANCHA_REFERENCIA", "FONTE_PRECO", "STATUS",
    "CODIGO_SINAPI", "CENTRO_CUSTO",
)
